export const bcuModules = [
  'Research Methodologies',
  'Audiences and Brand Development',
  'Digital Marketing Primer',
  'Planning and Strategy',
  'Contemporary Market Research Methods',
  'Methodologies for Digital Marketing Campaigns',
  'Collaborative Project',
  'Content Marketing',
  'Professional Practice',
  'Major Project (Visual Communication)',
];

export const bcuProjects = [
  {
    id: 'flock-together', title: 'Flock Together Audience Research',
    ownership: 'Team project · credited research contribution',
    summary: 'Audience and competitor research supporting a community and nature campaign proposal.',
    question: 'How could a nature and community organisation understand its audience and develop a more relevant proposition?',
    contribution: 'My credited role was research. I reviewed nature, social connection and mental health, researched comparable organisations and developed questions for primary research. Our team combined this work with a survey and a digital audit.',
    evidence: 'The earlier coursework review records a 37-person survey and research into BTO, RSPB and Black2Nature. The presentation developed audience personas, campaign objectives and measurement ideas.',
    outcome: 'The research supported a team campaign proposal. Strategy and other presentation sections remained the work of the named team members.',
    limits: 'A small exploratory survey cannot represent the wider population. The project demonstrates research and planning, with no measured campaign impact claimed.',
    skills: 'Audience research · Competitor analysis · Survey questions · Research synthesis',
  },
  {
    id: 'nandos', title: 'Nando’s Consumer Research',
    ownership: 'Academic research coursework',
    summary: 'Survey, observational and secondary research into the restaurant customer experience.',
    question: 'What could different research methods reveal about restaurant customers and their dining experience?',
    contribution: 'My coursework brought together survey research, observation and secondary sources. The fieldwork covered three Nando’s locations, examining customer demographics, activity levels, dining behaviour and waiting times.',
    evidence: 'The earlier review of the submitted coursework records the three-location observational exercise alongside survey and secondary research.',
    outcome: 'The exercise developed my ability to combine customer observations with other evidence and frame questions about service and audience needs.',
    limits: 'This was academic coursework. No sales uplift, operational change or representative customer estimate is claimed. The available record does not establish sole ownership of every research activity.',
    skills: 'Consumer research · Observation · Secondary research · Customer insight',
  },
  {
    id: 'mailchimp', title: 'Mailchimp Content Marketing Strategy',
    ownership: 'Team campaign concept · Content Marketing coursework',
    summary: 'B2B audience research, customer journeys and a Jenga-inspired creative campaign concept.',
    question: 'How could a content campaign explain Mailchimp’s value to small business owners and freelancers?',
    contribution: 'I contributed to coursework researching Mailchimp’s audiences, brand communication and marketing capabilities. Our team developed personas, conversion journeys and content ideas around making marketing simpler.',
    evidence: 'The research plan covers segmentation, behavioural targeting, automation, CRM, A/B testing and reporting. The team deck develops a Jenga video concept, supporting photo assets, a mock social post and a campaign timeline. A completed video asset was included in the original coursework uploads.',
    outcome: 'The team translated audience research into a coordinated content proposal and creative assets, with attention to brand consistency and the customer journey.',
    limits: 'This is an academic campaign concept. Targets in the draft are proposed objectives, not achieved results. Research into Mailchimp features does not imply a deployed automation or a live A/B test.',
    skills: 'Content strategy · Personas · Customer journeys · B2B research · Creative planning',
  },
  {
    id: 'peaky-blinders', title: 'Peaky Blinders Campaign Planning',
    ownership: 'Four-person team · Group 12',
    summary: 'Audience research and digital auditing informing a proposed entertainment campaign.',
    question: 'How could a campaign engage existing fans and attract new viewers to a final series?',
    contribution: 'I worked in a four-person team on a Peaky Blinders campaign proposal. Our presentation brought together interview findings, secondary research, competitor analysis and a social media audit.',
    evidence: 'The deck names Daniel as a team member and includes audience personas, a customer journey, a RACE funnel and proposed activity across social platforms, BBC channels and physical events. It also references Google Trends and SEMrush research.',
    outcome: 'Our team connected audience interests with creative proposals and suggested measures such as engagement, viewing and BBC iPlayer downloads.',
    limits: 'The campaign was proposed coursework, not commissioned work for the BBC. No campaign deployment, audience growth or sole ownership of the team output is claimed.',
    skills: 'Campaign planning · Digital audit · Audience personas · RACE · Measurement planning',
  },
];
