/**
 * GENERATED by projects/olist-reconstruction/rebuild.py from the recovered
 * Olist Dataset Clean v3.xlsx. Do not hand-edit these verified aggregates.
 * The source workbook is private, and this is NOT the original MMU PBIX.
 * Item value is listed item price, not payments, profit or realised revenue.
 */
export type OlistPeriod = 'all' | '2017' | '2018';

// [orders, delivered, late, eligible, reviewed, scoreSum, pricedOrders, itemValue, freight, items]
export const periodTotals: Record<OlistPeriod, [number,number,number,number,number,number,number,number,number,number]> = {
  "all": [98582,96394,7824,96386,97334,399760.0,97193,13401483.41,2222194.09,110929],
  "2017": [44550,43399,2878,43397,43883,180686.0,43763,6044291.39,969908.49,49890],
  "2018": [53724,52732,4942,52726,53150,217970.0,53124,7308058.93,1244990.24,60676]
};

// [purchaseMonth, orders, late, eligible, listedItemValue]
export const monthTrend: Array<[string,number,number,number,number]> = [
  ["2016-09",3,1,1,267.36],
  ["2016-10",304,3,261,48854.83],
  ["2016-12",1,0,1,10.9],
  ["2017-01",788,23,749,118421.58],
  ["2017-02",1730,53,1650,237762.43],
  ["2017-03",2640,142,2545,367541.13],
  ["2017-04",2391,181,2303,351234.14],
  ["2017-05",3659,128,3544,494819.22],
  ["2017-06",3215,121,3133,427303.92],
  ["2017-07",3958,133,3861,493366.82],
  ["2017-08",4291,139,4191,568256.49],
  ["2017-09",4235,216,4142,616322.07],
  ["2017-10",4568,237,4478,645418.95],
  ["2017-11",7451,1043,7288,996155.39],
  ["2017-12",5624,462,5513,727689.25],
  ["2018-01",7218,464,7067,927351.93],
  ["2018-02",6694,1048,6555,831419.96],
  ["2018-03",7188,1496,7003,965835.33],
  ["2018-04",6919,361,6783,987392.95],
  ["2018-05",6853,556,6749,993380.74],
  ["2018-06",6158,83,6094,862682.28],
  ["2018-07",6247,276,6130,888541.34],
  ["2018-08",6446,658,6345,851309.4],
  ["2018-09",1,0,0,145.0]
];

// [translatedCategory, all, 2017, 2018] by listed item price
export const categoryItemValues: Array<[string,number,number,number]> = [
  ["health_beauty",1257940.26,481564.92,771687.86],
  ["watches_gifts",1203281.4,491248.22,708672.94],
  ["bed_bath_table",1036309.28,497976.93,537853.36],
  ["sports_leisure",987411.11,451963.85,532113.62],
  ["computers_accessories",911688.58,404895.82,505393.44],
  ["furniture_decor",727815.99,336551.97,385870.19],
  ["cool_stuff",635148.52,393532.66,240504.86],
  ["housewares",631596.38,230684.09,399625.22],
  ["Other categories",6010291.89,2755872.93,3226337.44]
];

// [customerState, allOrders, allLate, allEligible, 2017Orders, 2017Late, 2017Eligible, 2018Orders, 2018Late, 2018Eligible]
export const customerStateBreakdown: Array<[string,number,number,number,number,number,number,number,number,number]> = [
  ["SP",41308,2386,40427,17505,793,17051,23695,1590,23283],
  ["RJ",12759,1664,12347,6167,695,5968,6544,969,6340],
  ["MG",11537,637,11347,5340,179,5234,6158,458,6079],
  ["RS",5431,382,5343,2636,163,2589,2771,219,2737],
  ["PR",4995,245,4920,2235,83,2192,2740,162,2708],
  ["SC",3610,346,3544,1700,146,1651,1900,200,1884],
  ["BA",3358,457,3256,1577,175,1527,1777,282,1726],
  ["DF",2125,147,2080,908,48,881,1211,99,1193],
  ["ES",2025,244,1995,962,77,945,1059,167,1047],
  ["GO",2007,160,1957,948,63,917,1051,97,1033],
  ["Other states",9427,1156,9170,4572,456,4442,4818,699,4696]
];
